- id: arxiv:2310.00093
  type: paper
  authors:
  - <strong>Ahmad Sajedi*</strong>
  - <strong>Samir Khaki*</strong>
  - Ehsan Amjadian
  - Lucy Z. Liu
  - Yuri A. Lawryshyn
  - Konstantinos N. Plataniotis
  publisher: IEEE/CVF International Conference on Computer Vision (ICCV)
  image: images/paper_teasers/ICCV23-DataDAM.png
  buttons:
  - type: source
    link: https://github.com/DataDistillation/DataDAM
  - type: website
    text: Project Page
    link: https://datadistillation.github.io/DataDAM/

- id: arxiv:2403.17921
  type: paper
  authors:
  - <strong>Samir Khaki</strong>
  - Konstantinos N. Plataniotis
  publisher: International Conference on Learning Representations (ICLR)
  image: images/paper_teasers/ICLR24-Transformer.png
  buttons:
  - type: source
    link: https://github.com/Skhaki18/optin-transformer-pruning
  - type: website
    text: Project Page
    link: http://www.samirkhaki.com/optin-transformer-pruning/

- id: arxiv:2401.01448
  type: paper
  authors:
  - <strong>Ahmad Sajedi</strong>
  - Samir Khaki
  - Yuri A. Lawryshyn
  - Konstantinos N. Plataniotis
  publisher: IEEE International Conference on Acoustics, Speech and Signal Processing (ICASSP)
  image: images/paper_teasers/ICASSP24-ProbMCL.jpg
  buttons:
  - type: source
    link: https://github.com/AhmadSajedii/ProbMCL
  - type: website
    text: Project Page
    link: https://ahmadsajedii.github.io/ProbMCL/

- id: arxiv:2405.01373
  type: paper
  authors:
  - <strong>Samir Khaki*</strong>
  - <strong>Ahmad Sajedi*</strong>
  - Kai Wang
  - Lucy Z. Liu
  - Yuri A. Lawryshyn
  - Konstantinos N. Plataniotis
  publisher: IEEE/CVF Conference on Computer Vision and Pattern Recognition -- Dataset Distillation Workshop (CVPR-DD)
  image: images/paper_teasers/CVPR24-ATOM.png
  buttons:
  - type: source
    link: https://github.com/DataDistillation/ATOM
  - type: website
    text: Project Page
    link: https://datadistillation.github.io/ATOM/

- id: arxiv:2310.17911
  type: paper
  authors:
  - <strong>Pai Chet Ng</strong>
  - Zhixiang Chi 
  - Yannick Verdie
  - Juwei Lu
  - Konstantinos N. Plataniotis
  publisher: Neural Information Processing Systems (NeurIPS) 2023 Datasets and Benchmarks Track
  image: images/background.jpg
  buttons:
  - type: source
    link: https://github.com/hyperspectral-skin/Hyper-Skin-2023
  - type: website
    text: Project Page
    link: https://hyper-skin-2023.github.io
